# Generated by Django 5.1.4 on 2025-01-14 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='name',
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_matches', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='balls_faced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_style',
            field=models.CharField(choices=[('right_hand', 'Right Hand'), ('left_hand', 'Left Hand')], default='right_hand', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='bowling_style',
            field=models.CharField(choices=[('right_arm_fast', 'Right Arm Fast'), ('right_arm_medium', 'Right Arm Medium'), ('right_arm_off_spin', 'Right Arm Off-Spin'), ('left_arm_fast', 'Left Arm Fast'), ('left_arm_medium', 'Left Arm Medium'), ('left_arm_orthodox_spin', 'Left Arm Orthodox Spin')], default='left_arm_medium', max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AddField(
            model_name='player',
            name='fifties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='hundreds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_vicecaptain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='outs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='overs_bowled',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='runs_conceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('batsman', 'Batsman'), ('bowler', 'Bowler'), ('all_rounder', 'All-Rounder'), ('wicket_keeper', 'Wicket Keeper')], default='batsman', max_length=20),
        ),
    ]
