# Generated by Django 5.1.4 on 2025-01-14 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_match_team_1_remove_match_team_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default='1980-01-01')),
                ('experience_years', models.IntegerField(default=0)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_head_coach', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=1000)),
                ('role', models.CharField(choices=[('batting_coach', 'Batting Coach'), ('bowling_coach', 'Bowling Coach'), ('fielding_coach', 'Fielding Coach'), ('fitness_coach', 'Fitness Coach'), ('assistant_coach', 'Assistant Coach')], default='assistant_coach', max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.team')),
            ],
        ),
    ]
