# Generated by Django 5.1.4 on 2025-01-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_player_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='match_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Batsman', 'batsman'), ('Bowler', 'bowler'), ('All Rounder', 'all_Rounder'), ('Wicket Keeper', 'wicket_keeper')], default='batsman', max_length=20),
        ),
    ]
