# Generated by Django 5.1.4 on 2025-01-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_player_match_played_alter_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='new_run',
            field=models.IntegerField(default=0),
        ),
    ]
