# Generated by Django 5.1.4 on 2025-01-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_player_new_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='new_ball_played',
            field=models.IntegerField(default=0),
        ),
    ]
