# Generated by Django 5.1.4 on 2025-01-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_player_new_ball_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coach_images/'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
