# Generated by Django 5.1.4 on 2025-01-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_coach_image_alter_coach_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='role',
            field=models.CharField(choices=[('Batting Coach', 'batting_coach'), ('Bowling Coach', 'bowling_coach'), ('Fielding Coach', 'fielding_coach'), ('Fitness Coach', 'fitness_coach'), ('Assistant Coach', 'assistant_coach')], default='assistant_coach', max_length=30),
        ),
    ]
