# Generated by Django 5.1.4 on 2025-01-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_tournament_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
