# Generated by Django 5.1.4 on 2025-01-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_alter_tournament_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='time',
        ),
    ]
