# Generated by Django 5.1.4 on 2025-01-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_remove_team_tournament_team_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='location',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='losses_against_ncc',
        ),
        migrations.RemoveField(
            model_name='team',
            name='matches_against_ncc',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins_against_ncc',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
