# Generated by Django 5.1.4 on 2025-01-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_team_description_team_location_team_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='opponent_team',
            field=models.CharField(blank=True, choices=[('KCMIT', 'kcmit'), ('SDC', 'sdc'), ('ORCHID', 'orchid'), ('KIST', 'kist'), ('IMS', 'ims'), ('MECHI', 'mechi')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
