# Generated by Django 5.1.4 on 2025-02-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_alter_match_opponent_team_delete_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='opponent_team',
        ),
    ]
