# Generated by Django 5.1.4 on 2025-02-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_remove_match_opponent_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='opponent_team',
            field=models.CharField(blank=True, choices=[('KCMIT', 'kcmit'), ('SDC', 'sdc'), ('ORCHID', 'orchid'), ('KIST', 'kist'), ('IMS', 'ims'), ('MECHI', 'mechi')], max_length=20, null=True),
        ),
    ]
