# Generated by Django 5.1.4 on 2025-02-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0021_match_opponent_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('matches_against_ncc', models.IntegerField(default=0)),
                ('wins_against_ncc', models.IntegerField(default=0)),
                ('losses_against_ncc', models.IntegerField(default=0)),
            ],
        ),
    ]
