# Generated by Django 5.1.4 on 2025-02-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0024_remove_team_losses_against_ncc'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.team'),
        ),
    ]
