# Generated by Django 5.1.4 on 2025-02-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0025_match_venue_alter_match_opponent_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, choices=[('KCMIT', 'kcmit'), ('SDC', 'sdc'), ('ORCHID', 'orchid'), ('KIST', 'kist'), ('IMS', 'ims'), ('MECHI', 'mechi')], max_length=50, null=True),
        ),
    ]
