# Generated by Django 5.1.4 on 2025-02-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0026_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
