# Generated by Django 5.1.4 on 2025-02-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0028_remove_match_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team_1_score',
            new_name='ncc_score',
        ),
    ]
