# Generated by Django 5.1.4 on 2025-02-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0030_alter_match_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
    ]
