# Generated by Django 5.1.4 on 2025-05-25 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0031_remove_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='ncc_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_2_score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='address',
        ),
        migrations.RemoveField(
            model_name='team',
            name='matches_against_ncc',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins_against_ncc',
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(default='Mulpani Cricket Ground', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
